-- Template Palette
-- By Tethrarxitet

return {
  Title = "Palette Name",
  Description = "Give a brief, formal description on what these colors are based off of.",
  Author = "Your name here",
  Icon = "rbxassetid://126072996706060",
  Colors = {
    {
      Color = {255, 0, 0},
      Name = "Full red",
      Description = "Only the purest of reds out there."
    },
    {
      Color = {52, 95, 117},
      -- Mo' colors
    }
  }
}
