-- Crayola Color Palette
-- By Tethrarxitet
-- As listed in https://en.wikipedia.org/wiki/List_of_Crayola_crayon_colors

return {
  Title = "Crayola Color Palette",
  Description = "This color palette includes all standard Crayola crayon colors that have an official website representation on Crayola.com.\nThis color palette and the creator is not endorsed or associated with Crayola.",
  Author = "Tethrarxitet",
  Icon = "rbxassetid://101148796859198",
  Colors = {
    
  }
}
