-- Crayola Color Palette
-- By Tethrarxitet
-- As listed in https://en.wikipedia.org/wiki/List_of_Crayola_crayon_colors

return {
	Title = "Crayola Color Palette",
	SmallDescription = "All standard Crayola crayon colors with an official website color representation.",
	Description = "This color palette includes all standard Crayola crayon colors that have an official website representation on Crayola.com.\nThis color palette and the creator is not endorsed or associated with Crayola.",
	Author = "Tethrarxitet",
	Icon = "rbxassetid://101148796859198",
	Colors = {
		{
			Color = "#ED0A3F",
			Name = "Red"
		},
		{
			Color = "#C32148",
			Name = "Maroon"
		},
		{
			Color = "#FD0E35",
			Name = "Scarlet"
		},
		{
			Color = "#C62D42",
			Name = "Brick Red"
		},
		{
			Color = "#CA3435",
			Name = "Mahogany"
		},
		{
			Color = "#B94E48",
			Name = "Chestnut"
		},
		{
			Color = "#FF3B29",
			Name = "Mango Tango"
		},
		{
			Color = "#FF3F34",
			Name = "Red-Orange"
		},
		{
			Color = "#FE4C40",
			Name = "Sunset Orange"
		},
		{
			Color = "#FE6F5E",
			Name = "Bittersweet"
		},
		{
			Color = "#FF9980",
			Name = "Vivid Tangerine"
		},
		{
			Color = "#FF6037",
			Name = "Outrageous Orange"
		},
		{
			Color = "#FF7034",
			Name = "Burnt Orange"
		},
		{
			Color = "#FF9966",
			Name = "Atomic Tangerine"
		},
		{
			Color = "#FF8833",
			Name = "Orange"
		},
		{
			Color = "#FFB97B",
			Name = "Macaroni and Cheese"
		},
		{
			Color = "#FF9933",
			Name = "Neon Carrot"
		},
		{
			Color = "#FFAE42",
			Name = "Yellow-Orange"
		},
		{
			Color = "#FBE7B2",
			Name = "Banana Mania"
		},
		{
			Color = "#FFCC33",
			Name = "Sunglow"
		},
		{
			Color = "#FCD667",
			Name = "Goldenrod"
		},
		{
			Color = "#FBE870",
			Name = "Yellow"
		},
		{
			Color = "#FFEE66",
			Name = "Unmellow Yellow"
		},
		{
			Color = "#F1E788",
			Name = "Green-Yellow"
		},
		{
			Color = "#B5B35C",
			Name = "Olive Green"
		},
		{
			Color = "#ECEBBD",
			Name = "Spring Green"
		},
		{
			Color = "#FFFF99",
			Name = "Canary"
		},
		{
			Color = "#DEE327",
			Name = "Inchworm"
		},
		{
			Color = "#E6FF66",
			Name = "Laser Lemon"
		},
		{
			Color = "#CCFF00",
			Name = "Electric Lime"
		},
		{
			Color = "#C5E17A",
			Name = "Yellow-Green"
		},
		{
			Color = "#7BA05B",
			Name = "Asparagus"
		},
		{
			Color = "#9DE093",
			Name = "Granny Smith Apple"
		},
		{
			Color = "#66FF66",
			Name = "Screamin' Green"
		},
		{
			Color = "#63B76C",
			Name = "Fern"
		},
		{
			Color = "#01A368",
			Name = "Green"
		},
		{
			Color = "#5FA777",
			Name = "Forest Green"
		},
		{
			Color = "#93DFB8",
			Name = "Sea Green"
		},
		{
			Color = "#33CC99",
			Name = "Shamrock"
		},
		{
			Color = "#1AB385",
			Name = "Mountain Meadow"
		},
		{
			Color = "#29AB87",
			Name = "Jungle Green"
		},
		{
			Color = "#00CC99",
			Name = "Caribbean Green"
		},
		{
			Color = "#00755E",
			Name = "Tropical Rain Forest"
		},
		{
			Color = "#01796F",
			Name = "Pine Green"
		},
		{
			Color = "#00CCCC",
			Name = "Robin's Egg Blue"
		},
		{
			Color = "#95E0E8",
			Name = "Aquamarine"
		},
		{
			Color = "#6CDAE7",
			Name = "Turquoise Blue"
		},
		{
			Color = "#2D383A",
			Name = "Outer Space"
		},
		{
			Color = "#76D7EA",
			Name = "Sky Blue"
		},
		{
			Color = "#0095B7",
			Name = "Blue-Green"
		},
		{
			Color = "#009DC4",
			Name = "Pacific Blue"
		},
		{
			Color = "#02A4D3",
			Name = "Cerulean"
		},
		{
			Color = "#93CCEA",
			Name = "Cornflower"
		},
		{
			Color = "#003366",
			Name = "Midnight Blue"
		},
		{
			Color = "#0066CC",
			Name = "Navy Blue"
		},
		{
			Color = "#1560BD",
			Name = "Denim"
		},
		{
			Color = "#0066FF",
			Name = "Blue (III)"
		},
		{
			Color = "#8CADDA",
			Name = "Blue Bell"
		},
		{
			Color = "#A9B2C3",
			Name = "Cadet Blue"
		},
		{
			Color = "#C3CDE6",
			Name = "Periwinkle"
		},
		{
			Color = "#4F69C6",
			Name = "Indigo"
		},
		{
			Color = "#8D90A1",
			Name = "Manatee"
		},
		{
			Color = "#7A89B8",
			Name = "Wild Blue Yonder"
		},
		{
			Color = "#6456B7",
			Name = "Blue-Violet"
		},
		{
			Color = "#8071B4",
			Name = "Purple Mountains' Majesty"
		},
		{
			Color = "#652DC1",
			Name = "Purple Heart"
		},
		{
			Color = "#6B3FA0",
			Name = "Royal Purple"
		},
		{
			Color = "#8359A3",
			Name = "Violet/Purple (II)"
		},
		{
			Color = "#C9A0DC",
			Name = "Wisteria"
		},
		{
			Color = "#803790",
			Name = "Vivid Violet"
		},
		{
			Color = "#C154C1",
			Name = "Fuchsia"
		},
		{
			Color = "#FC74FD",
			Name = "Pink Flamingo"
		},
		{
			Color = "#FF6EFF",
			Name = "Shocking Pink"
		},
		{
			Color = "#EE34D2",
			Name = "Razzle Dazzle Rose"
		},
		{
			Color = "#FF00CC",
			Name = "Hot Magenta"
		},
		{
			Color = "#E29CD2",
			Name = "Orchid"
		},
		{
			Color = "#843179",
			Name = "Plum"
		},
		{
			Color = "#FF00BB",
			Name = "Purple Pizzazz"
		},
		{
			Color = "#BB3385",
			Name = "Red-Violet"
		},
		{
			Color = "#A50B5E",
			Name = "Jazzberry Jam"
		},
		{
			Color = "#614051",
			Name = "Eggplant"
		},
		{
			Color = "#F653A6",
			Name = "Magenta"
		},
		{
			Color = "#DA3287",
			Name = "Cerise"
		},
		{
			Color = "#FF3399",
			Name = "Wild Strawberry"
		},
		{
			Color = "#FBAED2",
			Name = "Lavender (II)"
		},
		{
			Color = "#FFB7D5",
			Name = "Cotton Candy"
		},
		{
			Color = "#FFA6C9",
			Name = "Carnation Pink"
		},
		{
			Color = "#F7468A",
			Name = "Violet-Red"
		},
		{
			Color = "#E30B5C",
			Name = "Razzmatazz"
		},
		{
			Color = "#FDD7E4",
			Name = "Piggy Pink"
		},
		{
			Color = "#DB5079",
			Name = "Blush"
		},
		{
			Color = "#FC80A5",
			Name = "Tickle Me Pink"
		},
		{
			Color = "#F091A9",
			Name = "Mauvelous"
		},
		{
			Color = "#F78FA7",
			Name = "Pink Sherbert"
		},
		{
			Color = "#FF91A4",
			Name = "Salmon"
		},
		{
			Color = "#FF355E",
			Name = "Radical Red"
		},
		{
			Color = "#FD5B78",
			Name = "Wild Watermelon"
		},
		{
			Color = "#C7625A",
			Name = "Fuzzy Wuzzy"
		},
		{
			Color = "#FEBAAD",
			Name = "Melon"
		},
		{
			Color = "#E97451",
			Name = "Burnt Sienna"
		},
		{
			Color = "#AF593E",
			Name = "Brown"
		},
		{
			Color = "#9E5B40",
			Name = "Sepia"
		},
		{
			Color = "#926F5B",
			Name = "Beaver"
		},
		{
			Color = "#D27D46",
			Name = "Raw Sienna"
		},
		{
			Color = "#DEA681",
			Name = "Tumbleweed"
		},
		{
			Color = "#FA9D5A",
			Name = "Tan"
		},
		{
			Color = "#EDC9AF",
			Name = "Desert Sand"
		},
		{
			Color = "#FFCBA4",
			Name = "Peach"
		},
		{
			Color = "#FDD5B1",
			Name = "Apricot"
		},
		{
			Color = "#EED9C4",
			Name = "Almond"
		},
		{
			Color = "#837050",
			Name = "Shadow"
		},
		{
			Color = "#E6BE8A",
			Name = "Gold (II)"
		},
		{
			Color = "#C9C0BB",
			Name = "Silver"
		},
		{
			Color = "#DA8A67",
			Name = "Copper"
		},
		{
			Color = "#C88A65",
			Name = "Antique Brass"
		},
		{
			Color = "#000000",
			Name = "Black"
		},
		{
			Color = "#8B8680",
			Name = "Gray"
		},
		{
			Color = "#D9D6CF",
			Name = "Timberwolf"
		},
		{
			Color = "#FFFFFF",
			Name = "White"
		}
	}
}
